openapi: 3.0.0
servers:
  - url: 'http://127.0.0.1:8080'
info:
  description: >-
    Chat API.
  version: 1.0.0
  title: OpenAPI Chats
tags:
  - name: chat
    description: Everything about Chats
paths:
  /chat:
    post:
      tags:
        - chat
      summary: Get answer to the passed message
      operationId: chat
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BeerRequest'
        required: true
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '405':
          description: Invalid input
  /cooling-time:
    get:
      summary: Get cooling time for a beverage
      description: Returns the time it takes to cool a beverage to the desired temperature.
      parameters:
        - name: typeOfBeer
          in: query
          description: The type of the beer
          required: true
          schema:
            type: string
        - name: container
          in: query
          description: The container of the beer
          required: true
          schema:
            type: string
        - name: whereWasTheBeer
          in: query
          description: Where the beer was before cooling
          required: true
          schema:
            type: string
        - name: whereToCoolTheBeer
          in: query
          description: Where the beer is being cooled
          required: true
          schema:
            type: string
        - name: desiredTemperature
          in: query
          description: The desired temperature for the beer
          required: true
          schema:
            type: number
            format: float
        - name: selectedStartTime
          in: query
          description: The start time of the cooling process
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Cooling time in minutes
          content:
            application/json:
              schema:
                type: object
                properties:
                  coolingTime:
                    type: number
                    description: The time it takes to cool the beer in minutes
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
components:
  schemas:
    Message:
      title: Chat message
      description: A message, with author and date
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        message:
          type: string
        author:
          type: string
          description: Author of the message
          enum:
            - user
            - system
            - ai
    BeerRequest:
      title: Beer request
      description: Request object for beer cooling information
      type: object
      properties:
        typeOfBeer:
          type: string
          description: Type of beer
        container:
          type: string
          description: Bottle or container type
        whereWasTheBeer:
          type: string
          description: Location where the beer was stored
        whereToCoolTheBeer:
          type: string
          description: Location where the beer should be cooled
        desiredTemperature:
          type: string
          description: Desired temperature for cooling the beer