name: server_application
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ^3.3.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  chat_gpt_sdk: 3.0.3
  http: ^0.13.6
  openapi:
    path: ../openapi
  shelf_cors_headers: 0.1.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  test_process: ^2.1.0
